apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
{{ include "service.labels.standard" . | indent 4 }}
  name: {{ if .Values.storageClass.name }}"{{ .Values.storageClass.name }}"{{ else }}"{{ .Release.Name }}-sc"{{ end }}
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
  archiveOnDelete: {{ .Values.storageClass.archiveOnDelete | quote }}